config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :show]
  resources :posts do
    resources :post_votes, only: [:create]
    resources :comments, except: [:index, :show, :new] do
      resources :comment_votes, only: [:create]
    end
  end
  resource :session, only: [:create]

  root 'posts#index'

  get 'register' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post, touch: true
  has_many :comment_votes

  validates :content, presence: true

  def vote_count
    self.comment_votes.count
  end
end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_votes

  validates :title, presence: true
  validates :url, presence: true

  def vote_count
    self.post_votes.count
  end
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_votes
  has_many :comment_votes

  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password

  def voted_post?(post)
    post.post_votes.pluck(:user_id).include?(self.id)
  end

  def voted_comment?(comment)
    comment.comment_votes.pluck(:user_id).include?(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/comment_votes_controller.rb
class CommentVotesController < ApplicationController
  def create
    @vote = CommentVote.create(user_id: current_user.id, comment_id: params[:comment_id])
    redirect_to :back
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if logged_in?
      @comment = Comment.new(content: params[:comment][:content])
      @comment.user_id = current_user.id
      @comment.post_id = params[:post_id]
      @comment.save
    end
    redirect_to :back
  end

  def edit
    @comment = Comment.find(params[:id])
    @post = @comment.post
    unless @comment.user == current_user
      redirect_to :back
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @post = @comment.post
    if @comment.user == current_user
      @comment.content = params[:comment][:content]
      @comment.save
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    post = comment.post
    if comment.user == current_user
      comment.destroy
      redirect_to :back
    else
      redirect_to :back
    end
  end
end

app/controllers/post_votes_controller.rb
class PostVotesController < ApplicationController
  def create
    @vote = PostVote.create(user_id: current_user.id, post_id: params[:post_id])
    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc)
    @post_vote = PostVote.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @post_vote = PostVote.new
    @comment_vote = CommentVote.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(get_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to :back
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.user == current_user
      @post.update(get_params)
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user == current_user
      @post.destroy
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  def get_params
    params.require(:post).permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(get_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def get_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div>
  <fieldset>
    <legend><%=link_to comment.user.username, comment.user%></legend>
    <%= comment.content%><br>
    Votes: <%= comment.vote_count%>
    <%if logged_in? && !current_user.voted_comment?(comment)%>
      <%=form_for [@post, comment, @comment_vote] do |f|%>
        <%=f.submit 'Upvote'%>
      <%end%>
    <%end%>
  <%if comment.user == current_user%>
    <button><%=link_to 'Edit', edit_post_comment_path(comment.post, comment)%></button>
    <button><%= link_to 'Delete', [comment.post, comment], method: :delete%></button>
  <%end%>

  </fieldset>
</div>

app/views/comments/edit.html.erb
<%= form_for [@post, @comment] do |f|%>
  <fieldset>
    <%=f.label :Content%>
    <%=f.text_field :content%>

    <%=f.submit 'Submit'%>
  </fieldset>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<header>
  <%= link_to 'Home', root_path%>
  <% if logged_in? %>
  Logged in as <%= link_to current_user.username, current_user%>
  <%= link_to 'Logout', logout_path%>
  <%else%>
  <%= link_to 'Register', register_path%>
  <%= link_to 'Login', login_path%>
  <%end%>
</header>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f|%>
  <fieldset>
    <%=f.label :title%>
    <%=f.text_field :title%>

    <%=f.label :url%>
    <%=f.text_field :url%>

    <%=f.submit 'Submit'%>

  </fieldset>
<%end%>

app/views/posts/index.html.erb
<h1> Posts </h1>

<%= link_to "Write a new Post", new_post_path%>

<%@posts.each do |post|%>
  <h2><%= link_to post.title, post.url%> by <%=link_to post.user.username, "users/#{post.user_id}"%> </h2>
  <%= link_to 'Comments', post%><br>
  Votes: <%= post.vote_count %>
  <%if logged_in? && !current_user.voted_post?(post)%>
  <%=form_for [post, @post_vote] do |f|%>
      <%=f.submit 'Upvote'%>
  <%end%>
<%end%>
<%end%>

app/views/posts/new.html.erb
<%= form_for @post do |f|%>
  <fieldset>
    <%=f.label :title%>
    <%=f.text_field :title%>

    <%=f.label :url%>
    <%=f.text_field :url%>

    <%=f.submit 'Submit'%>

  </fieldset>
<%end%>

app/views/posts/show.html.erb
<h1><%= link_to @post.title, @post.url%></h1>
Votes: <%= @post.vote_count %>
<%if logged_in? && !current_user.voted_post?(@post)%>
  <%=form_for [@post, @post_vote] do |f|%>
      <%=f.submit 'Upvote'%>
  <%end%>
<%end%>
<%if @post.user == current_user%>
  <button><%=link_to 'Edit', edit_post_path%></button>
  <button><%= link_to 'Delete', @post, method: :delete%></button>
<%end%>

<%= form_for [@post, @comment] do |f|%>
  <fieldset>
    <%=f.label :content%>
    <%=f.text_field :content%>

    <%=f.submit 'Submit'%>
  </fieldset>
<%end%>

<%=render @comments%>

app/views/users/new.html.erb
<%= form_for @user do |f|%>
  <fieldset>
    <%=f.label :username%>
    <%=f.text_field :username%>

    <%=f.label :email%>
    <%=f.text_field :email%>

    <%=f.label :password%>
    <%=f.password_field :password%>

    <%=f.label :password_confirmation%>
    <%=f.password_field :password_confirmation%>

    <%=f.submit%>
  </fieldset>
<%end%>

app/views/users/show.html.erb
<h1><%= @user.username%></h1>

<ul>
<%@user.posts.each do |post|%>
<li><%= link_to post.title, post.url%></li>
<%= link_to "Comments", "/posts/#{post.id}"%>
<%end%>
</ul>